server:
  port: 8081

spring:
  application:
    name: payment-service
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: payment-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    

logging:
  level:
    org.springframework.kafka: DEBUG
    org.apache.kafka: DEBUG
    com.paymentservice: DEBUG